package api

import (
	"fmt"
	"strings"
)

// FormatErrorResponses formats the various errors generated by oapi-codegen into
// a standard go error
func FormatErrorResponses(unknownErr any) error {
	if unknownErr == nil {
		return nil
	}

	if notFoundResponse, ok := unknownErr.(*NotFoundResponse); ok {
		if notFoundResponse == nil {
			return nil
		}

		return fmt.Errorf(
			"request failed with errors: [%s: %s]",
			*notFoundResponse.Errors.Code,
			*notFoundResponse.Errors.Message,
		)
	}

	errorResponse, ok := unknownErr.(*ErrorResponse)
	if !ok {
		return fmt.Errorf("request failed with errors: unhandled error (%T)", unknownErr)
	}

	if errorResponse == nil {
		return nil
	}

	if errorResponse.Errors == nil || len(*errorResponse.Errors) == 0 {
		return fmt.Errorf("request failed with errors: unknown error")
	}

	msg := strings.Builder{}
	msg.WriteString("[")
	for i, err := range *errorResponse.Errors {
		if err.Code == nil && err.Message == nil {
			continue
		}

		msg.WriteString(fmt.Sprintf("%s: %s", *err.Code, *err.Message))
		if i < len(*errorResponse.Errors)-1 {
			msg.WriteString("; ")
		}
	}
	msg.WriteString("]")

	return fmt.Errorf("request failed with errors: %s", msg.String())
}

func coalesceErrors(errs ...any) error {
	for _, err := range errs {
		if err != nil {
			return FormatErrorResponses(err)
		}
	}

	return nil
}

func coalesceResponse[T any](ok *T, errs ...any) (*T, error) {
	if err := coalesceErrors(errs...); err != nil {
		return nil, err
	}

	return ok, nil
}

func (r GetAPIKeysResp) Unwrap() (*GetAPIKeysResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateAPIKeyResp) Unwrap() (*CreateAPIKeyResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r VerifyAPIKeyResp) Unwrap() (*VerifyAPIKeyResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON401, r.JSON429)
}

func (r DeleteAPIKeyResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetAPIKeyResp) Unwrap() (*GetAPIKeyResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r RotateAPIKeyResp) Unwrap() (*RotateAPIKeyResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetAPIsResp) Unwrap() (*GetApisResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddAPIsResp) Unwrap() (*CreateApisResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteAPIResp) Unwrap() (*DeleteAPIResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetAPIResp) Unwrap() (*GetAPIResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateAPIApplicationsResp) Unwrap() (*AuthorizeAppAPIResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteAPIAppliationScopeResp) Unwrap() error {
	return coalesceErrors(nil, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddAPIApplicationScopeResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetAPIScopesResp) Unwrap() (*GetAPIScopesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddAPIScopeResp) Unwrap() (*CreateAPIScopesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteAPIScopeResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetAPIScopeResp) Unwrap() (*GetAPIScopeResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateAPIScopeResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationsResp) Unwrap() (*GetApplicationsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateApplicationResp) Unwrap() (*CreateApplicationResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteLogoutURLsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetLogoutURLsResp) Unwrap() (*LogoutRedirectUrls, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddLogoutRedirectURLsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r ReplaceLogoutRedirectURLsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteCallbackURLsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetCallbackURLsResp) Unwrap() (*RedirectCallbackUrls, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r AddRedirectCallbackURLsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r ReplaceRedirectCallbackURLsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteApplicationResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationResp) Unwrap() (*GetApplicationResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateApplicationResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationConnectionsResp) Unwrap() (*GetConnectionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r RemoveConnectionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r EnableConnectionResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationPropertyValuesResp) Unwrap() (*GetPropertyValuesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateApplicationsPropertyResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateApplicationTokensResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetBillingAgreementsResp) Unwrap() (*GetBillingAgreementsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateBillingAgreementResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetBillingEntitlementsResp) Unwrap() (*GetBillingEntitlementsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateMeterUsageRecordResp) Unwrap() (*CreateMeterUsageRecordResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetBusinessResp) Unwrap() (*GetBusinessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateBusinessResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetConnectedAppAuthURLResp) Unwrap() (*ConnectedAppsAuthURL, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON404)
}

func (r RevokeConnectedAppTokenResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetConnectedAppTokenResp) Unwrap() (*ConnectedAppsAccessToken, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetConnectionsResp) Unwrap() (*GetConnectionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateConnectionResp) Unwrap() (*CreateConnectionResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteConnectionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetConnectionResp) Unwrap() (*Connection, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateConnectionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r ReplaceConnectionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetEnvironmentResp) Unwrap() (*GetEnvironmentResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteEnvironmentFeatureFlagOverridesResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetEnvironmentFeatureFlagsResp) Unwrap() (*GetEnvironmentFeatureFlagsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteEnvironmentFeatureFlagOverrideResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateEnvironmentFeatureFlagOverrideResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r ReadLogoResp) Unwrap() (*ReadEnvLogoResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteLogoResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddLogoResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetEnvironmentVariablesResp) Unwrap() (*GetEnvironmentVariablesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateEnvironmentVariableResp) Unwrap() (*CreateEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteEnvironmentVariableResp) Unwrap() (*DeleteEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetEnvironmentVariableResp) Unwrap() (*GetEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateEnvironmentVariableResp) Unwrap() (*UpdateEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetEventTypesResp) Unwrap() (*GetEventTypesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetEventResp) Unwrap() (*GetEventResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateFeatureFlagResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r DeleteFeatureFlagResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateFeatureFlagResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteIdentityResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetIdentityResp) Unwrap() (*Identity, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r UpdateIdentityResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetIndustriesResp) Unwrap() (*GetIndustriesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r ReplaceMFAResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetOrganizationResp) Unwrap() (*GetOrganizationResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateOrganizationResp) Unwrap() (*CreateOrganizationResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r UpdateOrganizationResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationHandleResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationsResp) Unwrap() (*GetOrganizationsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationFeatureFlagOverridesResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationFeatureFlagsResp) Unwrap() (*GetOrganizationFeatureFlagsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteOrganizationFeatureFlagOverrideResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationFeatureFlagOverrideResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r ReadOrganizationLogoResp) Unwrap() (*ReadLogoResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationLogoResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddOrganizationLogoResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r ReplaceOrganizationMFAResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetOrganizationPropertyValuesResp) Unwrap() (*GetPropertyValuesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationPropertiesResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationPropertyResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationSessionsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetOrganizationUsersResp) Unwrap() (*GetOrganizationUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateOrganizationUsersResp) Unwrap() (*UpdateOrganizationUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddOrganizationUsersResp) Unwrap() (*AddOrganizationUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r RemoveOrganizationUserResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteOrganizationUserAPIScopeResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r AddOrganizationUserAPIScopeResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r ResetOrgUserMFAAllResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetOrgUserMFAResp) Unwrap() (*GetUserMfaResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r ResetOrgUserMFAResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetOrganizationUserPermissionsResp) Unwrap() (*GetOrganizationsUserPermissionsResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r CreateOrganizationUserPermissionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r DeleteOrganizationUserPermissionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationUserRolesResp) Unwrap() (*GetOrganizationsUserRolesResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r CreateOrganizationUserRoleResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r DeleteOrganizationUserRoleResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationConnectionsResp) Unwrap() (*GetConnectionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r RemoveOrgConnectionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r EnableOrgConnectionResp) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetPermissionsResp) Unwrap() (*GetPermissionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON403)
}

func (r CreatePermissionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403)
}

func (r DeletePermissionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdatePermissionsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetPropertiesResp) Unwrap() (*GetPropertiesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreatePropertyResp) Unwrap() (*CreatePropertyResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r DeletePropertyResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdatePropertyResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetCategoriesResp) Unwrap() (*GetCategoriesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateCategoryResp) Unwrap() (*CreateCategoryResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r UpdateCategoryResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetRolesResp) Unwrap() (*GetRolesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateRoleResp) Unwrap() (*CreateRolesResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteRoleResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetRoleResp) Unwrap() (*GetRoleResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateRolesResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetRolePermissionsResp) Unwrap() (*RolePermissionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateRolePermissionsResp) Unwrap() (*UpdateRolePermissionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON403)
}

func (r RemoveRolePermissionResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetRoleScopesResp) Unwrap() (*RoleScopesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r AddRoleScopeResp) Unwrap() (*AddRoleScopeResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteRoleScopeResp) Unwrap() (*DeleteRoleScopeResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r SearchUsersResp) Unwrap() (*SearchUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetSubscribersResp) Unwrap() (*GetSubscribersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON403)
}

func (r CreateSubscriberResp) Unwrap() (*CreateSubscriberSuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403)
}

func (r GetSubscriberResp) Unwrap() (*GetSubscriberResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetTimezonesResp) Unwrap() (*GetTimezonesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteUserResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetUserDataResp) Unwrap() (*User, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateUserResp) Unwrap() (*UpdateUserResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateUserResp) Unwrap() (*CreateUserResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetUsersResp) Unwrap() (*UsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateUserFeatureFlagOverrideResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetUserIdentitiesResp) Unwrap() (*GetIdentitiesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r CreateUserIdentityResp) Unwrap() (*CreateIdentityResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r ResetUsersMFAAllResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetUsersMFAResp) Unwrap() (*GetUserMfaResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r ResetUsersMFAResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r SetUserPasswordResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetUserPropertyValuesResp) Unwrap() (*GetPropertyValuesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateUserPropertiesResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateUserPropertyResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r RefreshUserClaimsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r DeleteUserSessionsResp) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetUserSessionsResp) Unwrap() (*GetUserSessionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetWebHooksResp) Unwrap() (*GetWebhooksResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateWebHookResp) Unwrap() (*CreateWebhookResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r DeleteWebHookResp) Unwrap() (*DeleteWebhookResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r UpdateWebHookResp) Unwrap() (*UpdateWebhookResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}
