# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: kindeapi
output: client.gen.go
generate:
  client: true

compatibility:
  always-prefix-enum-values: true

output-options:
  skip-prune: true
  name-normalizer: ToCamelCaseWithInitialisms
  response-type-suffix: Result
  additional-initialisms:
    - API
  overlay:
    path: ./oapi-overlay.yaml
    strict: true
