# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: kindeapi
output: client.gen.go
generate:
  client: true
  models: true

compatibility:
  always-prefix-enum-values: true

output-options:
  skip-prune: true
  name-normalizer: ToCamelCaseWithInitialisms
  response-type-suffix: Result
  additional-initialisms:
    - ACS
    - APIs
    - HSL
    - IDP
    - IDs
    - SAML
    - SPA
    - SVG
    - URIs
    - URLs
  overlay:
    path: ./oapi-overlay.yaml
    strict: true
