package kindeapi

import (
	"fmt"
	"strings"
)

// FormatErrorResponses formats the various errors generated by oapi-codegen into
// a standard go error
func FormatErrorResponses(unknownErr any) error {
	if unknownErr == nil {
		return nil
	}

	if notFoundResponse, ok := unknownErr.(*NotFoundResponse); ok {
		if notFoundResponse == nil {
			return nil
		}

		return fmt.Errorf(
			"request failed with errors: [%s: %s]",
			*notFoundResponse.Errors.Code,
			*notFoundResponse.Errors.Message,
		)
	}

	errorResponse, ok := unknownErr.(*ErrorResponse)
	if !ok {
		return fmt.Errorf("request failed with errors: unhandled error (%T)", unknownErr)
	}

	if errorResponse == nil {
		return nil
	}

	if errorResponse.Errors == nil || len(*errorResponse.Errors) == 0 {
		return fmt.Errorf("request failed with errors: unknown error")
	}

	msg := strings.Builder{}
	msg.WriteString("[")
	for i, err := range *errorResponse.Errors {
		if err.Code == nil && err.Message == nil {
			continue
		}

		msg.WriteString(fmt.Sprintf("%s: %s", *err.Code, *err.Message))
		if i < len(*errorResponse.Errors)-1 {
			msg.WriteString("; ")
		}
	}
	msg.WriteString("]")

	return fmt.Errorf("request failed with errors: %s", msg.String())
}

func coalesceErrors(errs ...any) error {
	for _, err := range errs {
		if err != nil {
			return FormatErrorResponses(err)
		}
	}

	return nil
}

func coalesceResponse[T any](ok *T, errs ...any) (*T, error) {
	if err := coalesceErrors(errs...); err != nil {
		return nil, err
	}

	return ok, nil
}

func (r GetAPIKeysResult) Unwrap() (*GetAPIKeysResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateAPIKeyResult) Unwrap() (*CreateAPIKeyResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r VerifyAPIKeyResult) Unwrap() (*VerifyAPIKeyResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON401, r.JSON429)
}

func (r DeleteAPIKeyResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetAPIKeyResult) Unwrap() (*GetAPIKeyResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r RotateAPIKeyResult) Unwrap() (*RotateAPIKeyResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetAPIsResult) Unwrap() (*GetAPIsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddAPIsResult) Unwrap() (*CreateAPIsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteAPIResult) Unwrap() (*DeleteAPIResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetAPIResult) Unwrap() (*GetAPIResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateAPIApplicationsResult) Unwrap() (*AuthorizeAppAPIResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteAPIAppliationScopeResult) Unwrap() error {
	return coalesceErrors(nil, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddAPIApplicationScopeResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetAPIScopesResult) Unwrap() (*GetAPIScopesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddAPIScopeResult) Unwrap() (*CreateAPIScopesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteAPIScopeResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetAPIScopeResult) Unwrap() (*GetAPIScopeResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateAPIScopeResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationsResult) Unwrap() (*GetApplicationsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateApplicationResult) Unwrap() (*CreateApplicationResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteLogoutURLsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetLogoutURLsResult) Unwrap() (*LogoutRedirectURLs, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddLogoutRedirectURLsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r ReplaceLogoutRedirectURLsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteCallbackURLsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetCallbackURLsResult) Unwrap() (*RedirectCallbackURLs, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r AddRedirectCallbackURLsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r ReplaceRedirectCallbackURLsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteApplicationResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationResult) Unwrap() (*GetApplicationResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateApplicationResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationConnectionsResult) Unwrap() (*GetConnectionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r RemoveConnectionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r EnableConnectionResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetApplicationPropertyValuesResult) Unwrap() (*GetPropertyValuesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateApplicationsPropertyResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateApplicationTokensResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetBillingAgreementsResult) Unwrap() (*GetBillingAgreementsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateBillingAgreementResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetBillingEntitlementsResult) Unwrap() (*GetBillingEntitlementsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateMeterUsageRecordResult) Unwrap() (*CreateMeterUsageRecordResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetBusinessResult) Unwrap() (*GetBusinessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateBusinessResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetConnectedAppAuthURLResult) Unwrap() (*ConnectedAppsAuthURL, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON404)
}

func (r RevokeConnectedAppTokenResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetConnectedAppTokenResult) Unwrap() (*ConnectedAppsAccessToken, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetConnectionsResult) Unwrap() (*GetConnectionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateConnectionResult) Unwrap() (*CreateConnectionResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteConnectionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetConnectionResult) Unwrap() (*Connection, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateConnectionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r ReplaceConnectionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetEnvironmentResult) Unwrap() (*GetEnvironmentResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteEnvironmentFeatureFlagOverridesResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetEnvironmentFeatureFlagsResult) Unwrap() (*GetEnvironmentFeatureFlagsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteEnvironmentFeatureFlagOverrideResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateEnvironmentFeatureFlagOverrideResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r ReadLogoResult) Unwrap() (*ReadEnvLogoResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteLogoResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddLogoResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetEnvironmentVariablesResult) Unwrap() (*GetEnvironmentVariablesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateEnvironmentVariableResult) Unwrap() (*CreateEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteEnvironmentVariableResult) Unwrap() (*DeleteEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetEnvironmentVariableResult) Unwrap() (*GetEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateEnvironmentVariableResult) Unwrap() (*UpdateEnvironmentVariableResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetEventTypesResult) Unwrap() (*GetEventTypesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetEventResult) Unwrap() (*GetEventResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateFeatureFlagResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r DeleteFeatureFlagResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateFeatureFlagResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteIdentityResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetIdentityResult) Unwrap() (*Identity, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r UpdateIdentityResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetIndustriesResult) Unwrap() (*GetIndustriesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r ReplaceMFAResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetOrganizationResult) Unwrap() (*GetOrganizationResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateOrganizationResult) Unwrap() (*CreateOrganizationResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r UpdateOrganizationResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationHandleResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationsResult) Unwrap() (*GetOrganizationsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationFeatureFlagOverridesResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationFeatureFlagsResult) Unwrap() (*GetOrganizationFeatureFlagsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteOrganizationFeatureFlagOverrideResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationFeatureFlagOverrideResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r ReadOrganizationLogoResult) Unwrap() (*ReadLogoResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteOrganizationLogoResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddOrganizationLogoResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r ReplaceOrganizationMFAResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetOrganizationPropertyValuesResult) Unwrap() (*GetPropertyValuesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationPropertiesResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationPropertyResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateOrganizationSessionsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetOrganizationUsersResult) Unwrap() (*GetOrganizationUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateOrganizationUsersResult) Unwrap() (*UpdateOrganizationUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r AddOrganizationUsersResult) Unwrap() (*AddOrganizationUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r RemoveOrganizationUserResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r DeleteOrganizationUserAPIScopeResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r AddOrganizationUserAPIScopeResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r ResetOrgUserMFAAllResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetOrgUserMFAResult) Unwrap() (*GetUserMfaResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r ResetOrgUserMFAResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetOrganizationUserPermissionsResult) Unwrap() (*GetOrganizationsUserPermissionsResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r CreateOrganizationUserPermissionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r DeleteOrganizationUserPermissionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationUserRolesResult) Unwrap() (*GetOrganizationsUserRolesResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r CreateOrganizationUserRoleResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200)
}

func (r DeleteOrganizationUserRoleResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetOrganizationConnectionsResult) Unwrap() (*GetConnectionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r RemoveOrgConnectionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r EnableOrgConnectionResult) Unwrap() error {
	return coalesceErrors(r.JSON400, r.JSON403, r.JSON429)
}

func (r GetPermissionsResult) Unwrap() (*GetPermissionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON403)
}

func (r CreatePermissionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403)
}

func (r DeletePermissionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdatePermissionsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetPropertiesResult) Unwrap() (*GetPropertiesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreatePropertyResult) Unwrap() (*CreatePropertyResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r DeletePropertyResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdatePropertyResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetCategoriesResult) Unwrap() (*GetCategoriesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateCategoryResult) Unwrap() (*CreateCategoryResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r UpdateCategoryResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetRolesResult) Unwrap() (*GetRolesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateRoleResult) Unwrap() (*CreateRolesResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteRoleResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetRoleResult) Unwrap() (*GetRoleResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateRolesResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetRolePermissionsResult) Unwrap() (*RolePermissionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateRolePermissionsResult) Unwrap() (*UpdateRolePermissionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON403)
}

func (r RemoveRolePermissionResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetRoleScopesResult) Unwrap() (*RoleScopesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r AddRoleScopeResult) Unwrap() (*AddRoleScopeResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteRoleScopeResult) Unwrap() (*DeleteRoleScopeResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r SearchUsersResult) Unwrap() (*SearchUsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetSubscribersResult) Unwrap() (*GetSubscribersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON403)
}

func (r CreateSubscriberResult) Unwrap() (*CreateSubscriberSuccessResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400, r.JSON403)
}

func (r GetSubscriberResult) Unwrap() (*GetSubscriberResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r GetTimezonesResult) Unwrap() (*GetTimezonesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r DeleteUserResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetUserDataResult) Unwrap() (*User, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateUserResult) Unwrap() (*UpdateUserResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r CreateUserResult) Unwrap() (*CreateUserResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r GetUsersResult) Unwrap() (*UsersResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON429)
}

func (r UpdateUserFeatureFlagOverrideResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetUserIdentitiesResult) Unwrap() (*GetIdentitiesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r CreateUserIdentityResult) Unwrap() (*CreateIdentityResponse, error) {
	return coalesceResponse(r.JSON201, r.JSON400)
}

func (r ResetUsersMFAAllResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetUsersMFAResult) Unwrap() (*GetUserMfaResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r ResetUsersMFAResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r SetUserPasswordResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r GetUserPropertyValuesResult) Unwrap() (*GetPropertyValuesResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateUserPropertiesResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r UpdateUserPropertyResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400)
}

func (r RefreshUserClaimsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r DeleteUserSessionsResult) Unwrap() (*SuccessResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetUserSessionsResult) Unwrap() (*GetUserSessionsResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403, r.JSON404, r.JSON429)
}

func (r GetWebHooksResult) Unwrap() (*GetWebhooksResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r CreateWebHookResult) Unwrap() (*CreateWebhookResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r DeleteWebHookResult) Unwrap() (*DeleteWebhookResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}

func (r UpdateWebHookResult) Unwrap() (*UpdateWebhookResponse, error) {
	return coalesceResponse(r.JSON200, r.JSON400, r.JSON403)
}
