name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  ci:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - run: go vet -v ./...

      - run: golangci-lint run

      - run: go test -v ./...
